version: '3'

services:
  minetrack:
    build: .
    container_name: minetrack
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - minetrack_net
    ports:
      - "80:8080"
    restart: always

networks:
  minetrack_net:
    driver: bridge
